/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia.view;
import javax.swing.JTextArea;
import javax.swing.JDialog;

/**
 *
 * @author Gabriel
 */
public class ListarAluno extends javax.swing.JFrame {

    /**
     * Creates new form ListarAluno
     */
    public ListarAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buscaAlunoRadio = new javax.swing.JRadioButton();
        listaAlunoRadio = new javax.swing.JRadioButton();
        codigoAluno = new javax.swing.JTextField();
        buscaBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listar Aluno");
        setPreferredSize(new java.awt.Dimension(950, 553));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        jLabel1.setText("Listar Alunos");

        buttonGroup1.add(buscaAlunoRadio);
        buscaAlunoRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscaAlunoRadio.setText("Buscar aluno");
        buscaAlunoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaAlunoRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(listaAlunoRadio);
        listaAlunoRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaAlunoRadio.setText("Listar todos");
        listaAlunoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlunoRadioActionPerformed(evt);
            }
        });

        codigoAluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Código do Aluno"));

        buscaBotao.setText("Busca");
        buscaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buscaBotao)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(listaAlunoRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buscaAlunoRadio))
                                .addGap(18, 18, 18)
                                .addComponent(codigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(282, 282, 282))))
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscaAlunoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(listaAlunoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscaBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscaAlunoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaAlunoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaAlunoRadioActionPerformed

    private void listaAlunoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlunoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaAlunoRadioActionPerformed

    private void buscaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaBotaoActionPerformed
        // Ação do botão
        if(buscaAlunoRadio.isSelected()){
            int codigo = Integer.parseInt(codigoAluno.getText());
            //Funcao de busca por código
            //busca(codigo);
            System.out.println("Fazendo busca por aluno de código :" + 1);
            buscaAluno(codigo);
        }else{
            //função Listar Todos
            listarTodos();
            
        }
        
    }//GEN-LAST:event_buscaBotaoActionPerformed
    private void listarTodos(){
        JDialog resultado = new JDialog();
        resultado.setTitle("Listar todos");
        String dados = "Listar todos os alunos aqui";
        JTextArea areaDados = new JTextArea(dados);
        areaDados.setEditable(false);
        resultado.add(areaDados);
        resultado.setSize(500,500);
        resultado.setVisible(true);
    
    }
        private void buscaAluno(int i){
        JDialog resultado = new JDialog();
        resultado.setTitle("Busca aluno");
        String dados = "Listar os dados do aluno de codigo " + i + " aqui";
        JTextArea areaDados = new JTextArea(dados);
        areaDados.setEditable(false);
        resultado.add(areaDados);
        resultado.setSize(500,500);
        resultado.setVisible(true);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buscaAlunoRadio;
    private javax.swing.JButton buscaBotao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField codigoAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton listaAlunoRadio;
    // End of variables declaration//GEN-END:variables
}
